#!/bin/sh
command_exists() {
   command -v "$@" > /dev/null 2>&1
}
storage=${1:-/var/docker/lib}
if command_exists docker; then
   set -x 
   systemctl stop  docker.service
   systemctl disable docker.service
   rm -rf /usr/local/bin/docker*
   rm -rf /var/lib/docker
   rm -rf ${storage}
   rm -rf /etc/docker/*
fi
